# -------------------------------
# 1. 의존성 설치 단계 (Builder)
# -------------------------------
FROM node:24.12.0-alpine3.22 AS builder

LABEL name="bs6465"
LABEL description="capstone"

# OpenSSL 설치 (Prisma 요구사항)
RUN apk add --no-cache openssl

# 작업 디렉터리 설정
WORKDIR /usr/src/app

# 의존성 설치 (캐시 활용)
COPY package*.json pnpm-lock.yaml ./
RUN corepack enable

# prisma를 devDependencies에서도 설치하기 위해 --prod 제거 후 prune
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma/
# 로컬 prisma 사용 (버전 일치 보장)
RUN pnpm exec prisma generate

# production 의존성만 남기기
RUN pnpm prune --prod

# -------------------------------
# 2. 실행 단계 (Runner) - 최종 이미지
# -------------------------------
FROM node:24.12.0-alpine3.22

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json

COPY src ./src
COPY prisma ./prisma

# 애플리케이션 포트 노출
EXPOSE 4000

# 컨테이너 실행 명령어
CMD ["npx", "tsx", "src/index.ts"]