import type { UrgencyKeywordsConfig } from '../types/index.ts';

export const URGENCY_KEYWORDS: UrgencyKeywordsConfig = {
  naturalDisaster: {
    weight: 1.0,
    keywords: {
      지진: 10,
      쓰나미: 10,
      해일: 10,
      태풍: 9,
      홍수: 9,
      산사태: 9,
      폭우: 8,
      폭설: 8,
      폭풍: 8,
      침수: 8,
      범람: 8,
      호우: 7,
      대설: 7,
      강풍: 7,
      우박: 7,
      낙뢰: 6,
      가뭄: 5,
      한파: 6,
      폭염: 6,
      황사: 5,
      미세먼지: 4,
      산불: 9,
      화산: 10,
    },
  },
  accident: {
    weight: 0.9,
    keywords: {
      화재: 9,
      불이야: 10,
      폭발: 10,
      붕괴: 9,
      교통사고: 8,
      추돌: 7,
      전복: 8,
      탈선: 8,
      감전: 7,
      누출: 8,
      가스누출: 9,
      정전: 5,
      단수: 4,
      추락: 8,
      매몰: 9,
      총기: 10,
      테러: 10,
      칼부림: 10,
      묻지마: 9,
      인질: 10,
    },
  },
  lifeSafety: {
    weight: 0.7,
    keywords: {
      실종: 7,
      미아: 7,
      싱크홀: 6,
      도로파손: 5,
      정체: 3,
      통제: 5,
      대피: 8,
      대피소: 7,
      구조: 7,
      구급: 7,
      응급: 8,
      위험: 6,
      주의: 4,
      경보: 6,
      경고: 5,
      조심: 4,
      피하세요: 7,
      긴급: 7,
      사이렌: 6,
      '119': 6,
      신고: 5,
      출동: 6,
    },
  },
  health: {
    weight: 0.6,
    keywords: {
      전염병: 8,
      감염: 6,
      확진: 5,
      격리: 5,
      방역: 4,
      식중독: 6,
      오염: 5,
      유독: 7,
      독극물: 8,
      방사능: 9,
    },
  },
};

export const URGENCY_THRESHOLDS = {
  urgent: 7,
  caution: 4,
  normal: 0,
} as const;

export const ALERT_RADIUS = {
  urgent: 5000,
  caution: 2000,
} as const;

export const FREQUENCY_CONFIG = {
  radiusMeters: 1000,
  timeWindowMinutes: 60,
  boostThreshold: 3,
  boostAmount: 1.5,
} as const;
